= Come costruire Minie da sorgente
:Project: Minie

{Project} è un software gratuito e open-source.

Gli artifatti pre-costruiti possono essere scaricati da GitHub e dalla Repository Centrale di Maven,
tuttavia alcune persone preferiscono costruirli direttamente da sorgente.

Puoi anche costruire una copia della documentazione (il contenuto del sito).
Questo può essere utile se vuoi modificarne il contenuto o se
il tuo accesso a Internet è limitato o non accessibile.


== Artifatti di libreria

=== Build standard

La _costruzione standard_ della libreria {Project} include una libreria nativa non di debug, a precisione singola 
per ciascuna delle 13 piattaforme supportate da {Project}.

Ecco la procedura consigliata:

. Installa una https://adoptium.net/releases.html[Java Development Kit (JDK)],
  se non ne hai già una.
. Punta la variabile d'ambiente `JAVA_HOME` alla tua installazione JDK:
  (Il percorso potrebbe essere qualcosa di simile "C:\Program Files\Java\jre1.8.0_301"
  or "/usr/lib/jvm/java-8-openjdk-amd64/" o
  "/Library/Java/JavaVirtualMachines/liberica-jdk-17-full.jdk/Contents/Home" .)
.. usando una Bash o Zsh: `export JAVA_HOME="` *path dove installare* `"`
.. usando Windows Command Prompt: `set JAVA_HOME="` *path dove intallare* `"`
.. usuando PowerShell: `$env:JAVA_HOME = '` *path dove installare* `'`
. Scarica ed estrai il codice sorgente di {Project} da GitHub:
.. usando Git:
... `git clone https://github.com/stephengold/Minie.git`
... `cd Minie`
... `git checkout -b latest 7.7.0`
.. usando un browser web:
... naviga su https://github.com/stephengold/Minie/releases/latest
... scarica il "Codice sorgente (zip)"
... salva il file zip
... estrai il contenuto dellop zip
... entra nella directory estratta
. Esegui il wrapper Gradle per costruire l'intero progetto:
.. usando una Bash o una PowerShell o Zsh: `./gradlew build`
.. unando Windows Command Prompt: `.\gradlew build`

Dopo una build riuscita,
gli artifatti sarranno disponibili nella directory "MinieLibrary/build/libs".

=== Builds veloci

Oltre alla libreria, il progetto Minie include sottoprogetti per
risorse e applicazioni che richiedono tempo per essere create.
Per risparmiare tempo, puoi creare solo il sottoprogetto della libreria che ti interessa:

* usando Bash or PowerShell o Zsh: `./gradlew :MinieLibrary:build`
* usando Windows Command Prompt: `.\gradlew :MinieLibrary:build`

Per risparmiare ancora più tempo, puoi saltare i test automatici:

* usando Bash o PowerShell o Zsh: `./gradlew :MinieLibrary:assemble`
* usando Windows Command Prompt: `.\gradlew :MinieLibrary:assemble`

=== Installa artefatti

Puoi installare gli artefatti della build nella tua repository Maven locale:

* usando Bash o PowerShell o Zsh: `./gradlew install`
* usando Windows Command Prompt: `.\gradlew install`

=== Cleanup

Dopo una compilazione, puoi ripristinare il progetto a uno stato incontaminato:

* usando Bash o PowerShell o Zsh: `./gradlew clean`
* usando Windows Command Prompt: `.\gradlew clean`

== Personalizzazione delle librerie native

La build standard è molto conveniente.
Tuttavia, non è ottimale per molte situazioni.

=== Debug builds

Durante lo sviluppo dell'applicazione, dovrebbero essere utilizzate librerie native abilitate per il debug.
La maggior parte delle versioni di Minie fornisce una build "+debug" della libreria per questo scopo.
Puoi replicarlo aggiungendo l'opzione "-Pbtdebug" al comando build:

* usando Bash o PowerShell o Zsh: `./gradlew -Pbtdebug clean build`
* usando Windows Command Prompt: `.\gradlew -Pbtdebug clean build`

NOTA: non confondere l'opzione "-Pbtdebug" con "-Pdebug",
che ha un significato speciale per certe vecchie versioni di Gradle.

=== Build a doppia precisione

Alcune applicazioni possono trarre vantaggio dalle librerie native a doppia precisione.
La maggior parte delle versioni di Minie fornisce build "+dp" e "+debugdp" della libreria,
che puoi replicare aggiungendo l'opzione "-Pdp" al comando build.

=== Build multithread

Alcune applicazioni possono trarre vantaggio dalle librerie native multithread.
Alcune versioni di Minie forniscono build "+mt" della libreria,
che puoi replicare specificando l'opzione "-Pmt" nel comando build.

=== Builds ridotte

Il supporto di 13 piattaforme richiede 13 librerie native,
che si traduce in un JAR grande e grasso e (potenzialmente) un'applicazione gonfia.
Per risolvere il problema, alcune versioni di Minie forniscono build ridotte che
non supportano tutte le 13 piattaforme.
Questi includono:

* A "+big3" build (creabile usando l'opzione "-Pbig3")
  fornisce il supporto solo per le 3 piattaforme principali (Linux64, MacOSX64, and Windows64)
* A "+bare" build (creabile usando l'opzione "-Pbare")
  che non include *tutte* le librerie native.
* A "+droid" build (creabile usando l'opzione "-Pdroid")
  con supporto solo per le 4 piattaforme Android.

=== Ulteriore personalizzazione

Puoi personalizzare Minie per includere esattamente le librerie native di cui hai bisogno.

Per configurare quali librerie native saranno incluse nel JAR,
puoi modificare lo script "MinieLibrary/build.gradle".
Cerca la sezione in cui sono impostate le variabili `btf`.
Dovrebbe assomigliare a qualcosa di simile a questo:

[source,groovy]
----
btfAndroid_ARM7 = 'ReleaseSp'
btfAndroid_ARM8 = 'ReleaseSp'
btfAndroid_X86 = 'ReleaseSp'
btfAndroid_X86_64 = 'ReleaseSp'
btfLinux32 = 'ReleaseSp'
btfLinux64 = 'ReleaseSp'
btfLinux_ARM32 = 'hfReleaseSp'
btfLinux_ARM64 = 'ReleaseSp'
btfMacOSX32 = 'ReleaseSp'
btfMacOSX64 = 'ReleaseSp'
btfMacOSX_ARM64 = 'ReleaseSp'
btfWindows32 = 'ReleaseSp'
btfWindows64 = 'ReleaseSp'
----

Ad esempio, per includere solo la libreria nativa di Linux a 64 bit,
cambia le altre variabili `btf` in `''` e ricostruisci:

[source,groovy]
----
btfAndroid_ARM7 = ''
btfAndroid_ARM8 = ''
btfAndroid_X86 = ''
btfAndroid_X86_64 = ''
btfLinux32 = ''
btfLinux64 = 'ReleaseSp'
btfLinux_ARM32 = ''
btfLinux_ARM64 = ''
btfMacOSX32 = ''
btfMacOSX64 = ''
btfMacOSX_ARM64 = ''
btfWindows32 = ''
btfWindows64 = ''
----

Allo stesso modo, puoi personalizzare Minie
con la libreria nativa abilitata al debug per una piattaforma specifica:

[source,groovy]
----
btfAndroid_ARM7 = ''
btfAndroid_ARM8 = ''
btfAndroid_X86 = ''
btfAndroid_X86_64 = ''
btfLinux32 = ''
btfLinux64 = ''
btfLinux_ARM32 = ''
btfLinux_ARM64 = ''
btfMacOSX32 = ''
btfMacOSX64 = ''
btfMacOSX_ARM64 = ''
btfWindows32 = ''
btfWindows64 = 'DebugSp'
----

Allo stesso modo, puoi specificare librerie native a doppia precisione (con Dp).
per piattaforme specifiche:

[source,groovy]
----
btfAndroid_ARM7 = ''
btfAndroid_ARM8 = ''
btfAndroid_X86 = ''
btfAndroid_X86_64 = ''
btfLinux32 = ''
btfLinux64 = 'ReleaseDp'
btfLinux_ARM32 = ''
btfLinux_ARM64 = ''
btfMacOSX32 = ''
btfMacOSX64 = 'ReleaseDp'
btfMacOSX_ARM64 = 'ReleaseDp'
btfWindows32 = ''
btfWindows64 = 'ReleaseDp'
----

[NOTA]
====
Le librerie native non vengono pubblicate per ogni possibile combinazione di opzioni.
Ad esempio, se desideri librerie native Dp per piattaforme Android,
probabilmente dovrai costruirle tu stesso.
Per maggiori informazioni,
vedi https://github.com/stephengold/Libbulletjme[il progetto Libbulletjme].
====

== Contenuto del sito web

. Scarica ed estrai il codice sorgente da GitHub:
.. `git clone https://github.com/stephengold/Minie-site-it.git`
.. `cd Minie-site-it`
. Modifica "src/site/antora/playbook.yml" e sostituisci "/home/gattolfo/Documenti/github/Minie-site-it"
  con un percorso assoluto alla directory di checkout (3 posizioni).
. https://docs.antora.org/antora/latest/install-and-run-quickstart/#install-nodejs[Installa Node.js]
. Esegui Antora:
.. `npx antora src/site/antora/playbook.yml`

Dopo una costruzione riuscita,
la copia locale del sito si troverà nella directory "build/site".
