= Una panoramica delle applicazioni demo
:Project: Minie
:experimental:
:url-examples: https://github.com/stephengold/Minie/tree/master/MinieExamples/src/main/java/jme3utilities/minie/test

_Le applicazioni demo_ sono fornite per mostrare alcune caratteristiche di {Project}.
Le seguenti demo possono essere trovate qui:
{url-examples}[il "jme3utilities.minie.test" package del MinieExamples sub-project]:

* {url-examples}/BalanceDemo.java[`BalanceDemo`]
  mostra ragdoll che bilanciano il loro peso tra 2 piedi
* {url-examples}/BuoyDemo.java[`BuoyDemo`]
  mostra ragdoll con galleggiabilità
* {url-examples}/ConveyorDemo.java[`ConveyorDemo`]
  dimostra le modifiche del punto di contatto
* {url-examples}/DropTest.java[`DropTest`] (conosciuto anche come `MultiSphereDemo`)
  mostra la caduta di corpi rigidi di varie forme
* {url-examples}/ForceDemo.java[`ForceDemo`]
  mostra forze, coppie e impulsi applicati in assenza di gravità
* {url-examples}/JointDemo.java[`JointDemo`]
  mostra un robot strisciante composto da scatole e giunti a 6 gradi di libertà
* {url-examples}/NewtonsCradle.java[`NewtonsCradle`]
  dimostra restituzione dinamica e giunzioni punto-punto
* {url-examples}/Pachinko.java[`Pachinko`]
  mostra le forme di collisione composte e la fisica 2-D
* {url-examples}/PoolDemo.java[`PoolDemo`]
  dimostra 3 tipi di attrito dinamico
* {url-examples}/RopeDemo.java[`RopeDemo`]
  dimostra la simulazione delle corde usando  `DynamicAnimControl`
* {url-examples}/SeJointDemo.java[`SeJointDemo`] 
  dimostra vari tipi di giunti fisici single-ended
* {url-examples}/SplitDemo.java[`SplitDemo`]
  dimostra la scissione dinamica di corpi rigidi
* {url-examples}/SweepDemo.java[`SweepDemo`]
  dimostra l'uso di `sweepTest()` per rilevare i colpi di spada
* {url-examples}/TargetDemo.java[`TargetDemo`]
  mostra uno sparo di una palla su vari bersagli 
* {url-examples}/TestDac.java[`TestDac`]
  mostra `DynamicAnimControl` applicato a vari modelli
* {url-examples}/TestGearJoint.java[`TestGearJoint`]
  mostra un giunto di marcia
* {url-examples}/TestSoftBody.java[`TestSoftBody`]
  dimostra la fisica del corpo molle senza `SoftBodyControl`
* {url-examples}/TestSoftBodyControl.java[`TestSoftBodyControl`]
  dimostra la fisica del corpo molle con un `SoftBodyControl`
* {url-examples}/TrackDemo.java[`TrackDemo`]
  mostra la cinematica inversa usando `IKController`
* {url-examples}/WatchDemo.java[`WatchDemo`]
  mostra la cinematica inversa testa/occhio per vari modelli
* {url-examples}/Windlass.java[`Windlass`]
  mostra la simulazione della fune utilizzando corpi rigidi

(Non tutte le applicazioni nel pacchetto sono intese come demo;
quelle non elencati sopra sono principalmente a scopo di test.)

Per alcune delle demo, i video walkthrus sono disponibili su YouTube.


== Interfaccia utente

Le demo sono controllate principalmente dall'input da tastiera.
Ognuno include un _help node_
che visualizza una breve descrizione della funzione di ciascun tasto.

NOTA: le descrizioni seguenti presuppongono una tastiera con layout "US" (QWERTY).
Sulle tastiere con altri layout, i tasti possono essere etichettati in modo diverso:
fare riferimento ai nodi della guida per le etichette delle chiavi localizzate.

Per comodità, la mappatura delle chiavi alle azioni è in parte standardizzata.
Nella maggior parte delle demo:

* kbd:[H] alterna il nodo di aiuto tra le versioni ridotte a icona e a grandezza naturale,
* kbd:[F5] attiva/disattiva la visibilità della sovrapposizione delle statistiche di rendering,
* kbd:[O] dumps spazio fisico sulla console,
* kbd:[C] dumps posizione della telecamera sulla console e
* kbd:[Esc] termina l'applicazione.

Per il controllo della fotocamera, tutte le demo usano
lo standard `FlyByCamera` con `setDragToRotate(true)`.
Ciò significa che puoi ruotare la fotocamera
trascinando con il tasto sinistro del mouse (LMB).
Inoltre:

* kbd:[W] e kbd:[S] muovono la fotocamera avanti e indietro, rispettivamente,
* kbd:[A] e kbd:[D] muovono la fotocamera a sinistra ea destra, rispettivamente,
* kbd:[Q] e kbd:[&uarr;] alzare la fotocamera, e
* kbd:[Z] e kbd:[&darr;] abbassano la fotocamera.

Alcune demo (come `DropTest` e `TargetDemo`)
si affidano interamente alla visualizzazione di debug per il rendering degli oggetti fisici.
Altri (come `TestDac` e `PoolDemo`) usano controlli fisici.
Quando sono in uso i controlli fisici,
kbd:[/] attiva e disattiva la visualizzazione del debug.
