= Come funziona Minie
:Cplusplus: C&#43;&#43;
:Project: Minie
:url-enwiki: https://en.wikipedia.org/wiki

Per la simulazione fisica e per il rilevamento delle collisioni,
{Project} usa https://pybullet.org/wordpress[the _Bullet Physics SDK_],
un simulatore fisico 3-D open-source e affidabile,
rilasciato sotto https://github.com/bulletphysics/bullet3/blob/master/LICENSE.txt[Zlib license].

Per consentire una simulazione efficente delle mesh in movimento,
{Project} incorpora anche
https://github.com/kmammou/v-hacd[L'algoritmo di decomposizione convessa approssimata volumetrica-gerarchica _(V-HACD)_] di Khaled Mamou.

== Librerie native

Bullet e V-HACD sono scritte in {Cplusplus}, quindi {Project} utilizza
https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/intro.html[Java Native Interface (JNI)]
per accedere ai loro metodi e oggetti.

Tutto il codice sorgente {Cplusplus} utilizzato nel {Project}
(incluso uno snapshot modificato di Bullet, uno snapshot di V-HACD, e qualche "codice colla")
si trovano nella https://github.com/stephengold/Libbulletjme[ repository Libbulletjme].
Prima di inizializzare oggetti fisici,
una applicazione {Project} deve {url-enwiki}/Dynamic_loading[caricare dinamicamente]
una _libreria nativa_ di questo codice,
compilata per {url-enwiki}/Computing_platform[la piattaforma]
su cui l'app è in esecuzione.

Il progetto Libbulletjme pubblica librerie native
per le 13 piattaforme supportate da {Project}:

* Windows (32-bit and 64-bit),
* Linux (x86-64, x86, armhf, and aarch64),
* macOS (x86-64, IA-32, and ARM64), e
* Android (armeabi-v7a, arm64-v8a, x86, and x86_64).

NOTA: le versioni 32-bit e 64-bit dello stesso sistema operativo
contano come piattaforme distinte!

Sulle piattaforme desktop, JMonkeyEngine carica automaticamente
le librerie native corrette
durante l'inizializzazione della classe `JmeDesktopSystem`
se rileva la classe Minie `NativeMeshUtil`.
Su Android, la libreria nativa è caricata (se presente) 
durante l'inizializzazione statica della classe `JmeAndroidSystem`.

== Collisioni con oggetti, spazi e forme

Il rilevamento di collisioni è organizzato intorno a _oggetti di collisione_ 
che interagiscono nel contesto di uno _spazione di collisione_.
Gli oggetti di collisione possono essere _morbidi_ (forma variabile) oppure _rigidi_ (forma non variabile).
Gli oggetti rigidi possono essere _movibili_ (in movimento) o _statici_ (non in movimento).
In oltre gli oggetti movibili possono essere _dinamici_ (controllati da {url-enwiki}/Force[forze],
{url-enwiki}/Torque[rotazioni] e {url-enwiki}/Impulse_(physics)[impulsi])
oppure _cinematici_ (controllati direttamente da un calcolatore esterno).

In {Project}, gli spazi di collisione che simulano forze, rotazioni e impulsi 
sono indicati come _physics spaces_.

Di per sé, gli oggetti di collisione sono invisibili,
mentre gli spatial scene-graph non hanno effetto sulla fisica.
Per visualizzare un oggetto di collisione, questo deve essere associato
con uno o più spatial scene-graph.
Per scopi di debugging, {project} può visualizzare 
gli oggetti di collisione autogenerando degli spatial.
Per una visualizzazione completamente personalizzata, utilizzare un _physics control_
per associare oggetti di collisione a spatial.

Ogni oggetto di collisione rigido si collega a _collision shape_
che descrive la forma della sua superfice.
Molte collision shapes sono _scalabili_,
permettendo di ingrandire o rimpicciolire oggetti
semplicemente variando i fattori di scala della forma.

== Sistema di coordinate e unità

La location assoluta e l'orientazione di un oggetto di collisione sono quantificate
in _coordinate dello spazio fisico_,
basate su un sistema di coordinate cartesiane destrorse.
Queste solitamente corrispondono alle coordinate della scena (world cordinate).
Tuttavia, {project} supporta il ridimensionamento dello spazio fisico relativo alla scena,
in questo caso le _coordinate dello spazio fisico_ (psu)
potrebbero differire dalle unità del mondo (wu).


Con notevoli eccezioni,
{Project} non utilizza dimensioni reali per le distanze.
La ducumentazione utilizza unità dello spazio fisico (physics-space units),
che potrebbero essere anni luce o millimetri, in base all'applicazione.

{Project} non specifica nemmeno quale asse rappresenta la direzione "su",
Se utilizzi un sistema di cordinate Y-up con psu di un metro,
allora la gravità di default di {Minie} 
sarà approssimativamente simile alla gravità della superfice terrestre.
Tuttavia, ci sono buone ragioni per utilizzare unità dello spazio fisico diverse dai metri.

Le posizioni relative al centro degli oggetti di collisione e soggette alle sue rotazioni 
sono quantificate usando _coordinate locali_.
La documentazione distingue _coordinate locali scalate_ (misurate in psu)
dalle _coordinate di forma_ (che dipendono dai fattori di scala)

== Tempo discreto e rilevamento delle collisioni

All'interno di uno spazio fisico, la simulazione avviene in passi discreti.
Mentre è possibile variare il tempo da step a step,
uno step temporale fisso tende a produrre risultati più riproducibili.

Ogni step consiste di 4 _fasi_:

. _forward dynamics parte uno_,
  per applicare forze e momenti noti 
  e prevedere la posizione successiva di ogni oggetto di collisione,
. _broadphase collision detection_,
  per determinare rapidamente (usando riquadri di delimitazione allineati con gli assi)
  quali coppie di oggi potrebbero entrare in collisione,
. _narrowphase collision detection_,
  per calcolare gli effettivi contatti (se presenti), e 
. _forward dynamics parte due_,
  per applicare forze di contatto, risolvere vincoli, e aggiornare posizioni.

Le collisioni sono inviate ai listerner registrati allo spazio.
Per oggetti con movimenti veloci, 
{Project} offre il rilevamento continuo opzionale delle collisioni (CCD)
usando delle swept spheres.
Le collisioni rilevate da CCD sono inviate agli stessi listener.

== App states

Per semplificare la creazione e la gestione dello spazio fisico
{Project} fornisce gli _app states_
Il più semplice è `BulletAppState`; che si occupa di gestire un singolo 
spazio senza nessun oggetto morbito o multioggetti.
La simulazione dello spazio può essere posizionata nel thread di render
oppure in un _thread fisico_ dedicato.
In entrambi i casi l'app state cerca di sincronizzarsi in tempo reale 
durante ogni fotogramma realizzato. 

La visualizzazione del debug può essere attivata o disattivata, semplicemente impostando un parametro.

== buffer diretti, garbage collection, and threading

I buffer diretti usati in {Project} devono avere un byte order nativo.

Tutti gli altri oggetti nativi creati da {Project} sono attentamente tracciati 
usando riferimenti deboli.

La riuscita inizializzazione di una libreria nativa causa in {Project}
l'avvio di un demone chiamato "Physics Cleaner".
Il suo compito è quello di liberare tutti gli oggetti nativi monitorati 
che corrispondono a oggetti java che sono stati liberati dal garbage collector. 

Come miglioramento delle prestazioni,
{Project} può parallelizzare determinati cicli dor sulle piattaforme che supportano OpenMP.
Per abilitare questa feature, è necessario caricare una libreria nativa multithread.

== Prossimi passi

Per più dettagli sulla fisica Bullet puoi scaricare il
https://github.com/bulletphysics/bullet3/blob/master/docs/Bullet_User_Manual.pdf[manuale utente di Bullet].

Per acquisire esperienza pratica, 
puoi procedere alla xref:minie-library-tutorials:add.adoc[prima pagina del tutorial].
