= Overview del progetto {Project}
:Project: Minie
:url-enwiki: https://en.wikipedia.org/wiki

_{Project}_ è una libreria di {url-enwiki}/Physics_engine[simulazione fisica] 3-D  
per https://jmonkeyengine.org[JMonkeyEngine]
che porta i giochi basati sulla fisica a un livello superiore.

Puoi usarla per:

* aggiungere consistenza a muri, personaggi, proiettili, paesaggi, e veicoli,
* rilevare collisioni tra forme complesse,
* eseguire test di contatto, traiettorie, scansioni,
* simulare personaggi e costruzioni che crollano in tempo reale,
* simulare vestiti, corde, e volumi deformabili,
  comprese le loro interazini con altri corpi rigidi e loro stessi.

Forked da https://github.com/jMonkeyEngine-Contributions/Jme3Bullet[the jme3-bullet library]
nel 2018, Minie aggiunse molte features utili
ma comunque preservando la maggior parte delle 
{url-enwiki}/Application_programming_interface[API] jme3-bullet.
La maggior parte degli esempi fisici di JMonkeyEngine possono usare minie senza modifiche, in oltre minie fornisce i propri tutorial ed esempi per aiutarti a iniziare.

Tutti i software nel progetto {Project} sono gratis e open-source,
incluse le librerie stesse, le demo, i tutorial, le utiliti,
e i software usati per eseguire la build, i test e infine per eseguirli.

Il software di simulazione sottostante è
https://pybullet.org/wordpress[_Bullet_], un maturo simulatore di fisica in tempo reale.
Sebbene Bullet sia scritto in {url-enwiki}/C%2B%2B[C&#43;&#43;],
non avrai bisogno di nessuna conoscenza di C&#43;&#43; per usare {Project}.


== Avvertenze

Il focus di {Project}  è sul simulare le 
{url-enwiki}/Classical_mechanics[meccaniche classiche]
in sufficiente dettaglio da aggiungere verisimilitudine ai giochi 3-D.
Non è inteso per i {url-enwiki}/Platform_game[platformers] 2-D,
né per ricerche scientifiche.
Per la fisica 2-D considera di usare http://www.dyn4j.org/[dyn4j] invece.

Per poter utilizzare l'ultima versione di {Project},
avrai bisogno delle librerie 3.6.1 JMonkeyEngine.
Per più informazioni sulle dipendenze di {Project} controlla xref:depends.adoc[La pagina delle dipendenze].

Come JMonkeyEngine, {Project} e la sua documentazione suppone un certo di livello di abilità con il
{url-enwiki}/Java_(programming_language)[linguaggio di programmazione Java].
Questo progetto non è pensato per i non programmatori,
ne per i programmatori senza esperienza Java.
Allo stesso modo, si presume una certa familiarità con la grafica 3D e la matematica vettoriale.

Anche se una conoscenza della meccanica classica è supposta,
molti dei suoi termini tecnici sono linkati (al primo utilizzo) 
all'articolo rilevante nella Wikipedia inglese.

https://raw.githubusercontent.com/stephengold/Minie/master/LICENSE[La licenza BSD-style del progetto]
declina ogni responsabilità per vizi.
Si prega di non utilizzare questo software in applicazioni pensate la sicurezza.


== Ricevere aiuto

Per cercare aiuto autonomamente, fare uso di:
xref:minie-library-tutorials:add.adoc[Pagina dei tutorials],
https://stephengold.github.io/Minie/javadoc/master[javadoc], e
https://github.com/stephengold/Minie[codice sorgente].

Il Forum/Hub di JMonkeyEngine è un buon luogo dove fare domande tecniche.
Le categorie più rilevanti sono:

* https://hub.jmonkeyengine.org/c/user-code-projects/minie/63[Discussioni e progetti : Minie] e
* https://hub.jmonkeyengine.org/c/troubleshooting/physics/17[Risoluzione problemi : Physics].

Per problemi che è meglio gestire privatamente, la mia mail è disponibile qui:
https://stephengold.github.io/[la mia homepage] e nel codice sorgente.


== Il nome

Il progetto prende il nome da
{url-enwiki}/Claude-%C3%89tienne_Mini%C3%A9[_Claude-Étienne Minié_],
che nel 1846 progettò proiettili migliorati per fucili.
E' un gioco di parole, non intendo ne denigrarlo ne glorificarlo.

La pronuncia inglese preferita è approssimativamente "min-YAY",
ma anche "MIN-ee" è accettabile.


== Prossimi passi

Se sei curioso di come {Project} funziona,
procedi alla xref:implementation.adoc[pagina di implementazione].

Per acquisire esperienza pratica,
procedi alla xref:minie-library-tutorials:add.adoc[prima pagina del tutorial].
