= Come aggiungere Minie a un progetto esistente
:Project: Minie
:experimental:
:page-pagination:
:url-api: https://stephengold.github.io/Minie/javadoc/master/com/jme3/bullet

TIP: se stai creando un applicazione JMonkeyEngine desktop da zero,
 https://github.com/stephengold/BasicGame-on-Gradle[il progetto BasicGame-on-Gradle]
fornisce un buon punto di partenza.

Aggiungere {Project} a un progetto esistente JMonkeyEngine richiede 7 step:

. Rimuovere qualsiasi libreria che potrebbe interferire con Minie.
. Aggiungere librerie al classpath.
. Caricare la libreria nativa.
. Crea, configura e collega un
 {url-api}/BulletAppState.html[`BulletAppState`],
   se l'applicazione non lo ha già fatto.
. Configura lo {url-api}/PhysicsSpace.html[`PhysicsSpace`],
  se l'applicazione non lo ha già fatto.
. Crea controlli fisici, oggetti di collisione e giunti, e aggiungili allo spazio fisico, se l'applicazione non lo ha già fatto.
. Testa e ottimizza se necessario.

== Rimuovere le librerie che potrebbero causare interferenze.

Se in qualsiasi directory in cui potrebbe essere eseguita l'applicazione ci sono file denominati 'libbulletjme.so', 'bulletjme.dll' o 'libbulletjme.dylib', dovresti rimuovere quei file. Questi nomi di file sono utilizzati da JMonkeyEngine quando carica la libreria nativa, e non desideri che venga caricata quella sbagliata!

Inoltre, Minie sostituisce (e quindi è incompatibile con)
le seguenti librerie di JMonkeyEngine:

* jme3-bullet
* jme3-bullet-native
* jme3-bullet-native-android, e
* jme3-jbullet.

Prima di aggiungere Minie, dovresti rimuovere queste librerie dal progetto in modo 
che non interferiscano con Minie.

=== Progetti costruiti con Gradle.

. Cerca gli artefatti con questi nomi nella sezione delle dependencies 
  dei file '*.gradle' del progetto.
. Rimuovi quelle dipendenze.

=== Progetti costruiti con Maven.

. Cerca gli artefatti con quegli ID nella sezione delle dependencies
 del file "pom.xml" del progetto.
. Rimuovi quelle dipendenze.

=== Progetti costruiti con Ant.

Apri le proprietà del progetto nell'IDE (JME SDK o NetBeans):

. Fai clic con il tasto destro del mouse sul progetto (non sulla sua cartella "assets") nella finestra "Progetti".
. Seleziona il menu: Proprietà[] per aprire il dialogo delle "Proprietà del Progetto".
. Sotto 'Categorie:', clicca su btn:[Librerie].
. Clicca sulla scheda btn:[Compila].
. Cerca librerie incompatibili nell'elenco 'Librerie di Compilazione'.
 Selezionale e clicca sul pulsante btn:[Rimuovi].
. Clicca sul pulsante btn:[OK] per chiudere il dialogo delle 'Proprietà del Progetto'.

== Aggiungi librerie al percorso di classe.

{Project} viene pre-costruito come una singola libreria che include sia classi Java che 
librerie native.
La libreria {Project} dipende da:

* la libreria standard jme3-terrain,
* https://github.com/Simsilica/SimMath[la libreria SimMath di Simsilica], e
* https://github.com/stephengold/Heart[la libreria Heart],

e queste librerie dipendono da altre librerie JVM.

Per i progetti costruiti utilizzando Gradle o Maven, di solito è sufficiente specificare
la dipendenza dalla libreria {Project}. Gli strumenti di build dovrebbero risolvere 
automaticamente le restanti dipendenze.

=== Progetti costruiti con Gradle.

Aggiungi al file "build.gradle" del progetto:

[source,groovy]
----
repositories {
    mavenCentral()
}
dependencies {
    implementation 'com.github.stephengold:Minie:7.7.0'
}
----

Per alcune versioni più datate di Gradle,
è necessario sostituire `implementation` con `compile`.

=== Progetti costruiti con Maven.

Aggiungi al file "pom.xml" del progetto:

[source,xml]
----
<repositories>
    <repository>
      <id>mvnrepository</id>
      <url>https://repo1.maven.org/maven2/</url>
    </repository>
</repositories>

<dependency>
  <groupId>com.github.stephengold</groupId>
  <artifactId>Minie</artifactId>
  <version>7.7.0</version>
</dependency>
----

=== Progetti costruiti con Ant.

Ant non gestisce le dipendenze trasitive, quindi dovrai risolverle manualmente. 
Inoltre, per utilizzare l'ultima versione di {Project}, avrai bisogno delle librerie 
JMonkeyEngine versione 3.6.1. (Puoi comunque utilizzare JME 3.2 o 3.3 SDK.) 
Per ulteriori informazioni sulle librerie di cui {Project} dipende, consulta la pagina delle 
dipendenze delle versioni della libreria: xref:ROOT:depends.adoc[pagina delle dipendenze delle versioni delle librerie].

Scarica la libreria {Project} e le 
sue dipendenze da GitHub e/o Maven Central:

* https://github.com/stephengold/Minie/releases/latest
* https://github.com/stephengold/Heart/releases/tag/8.7.0
* https://github.com/Simsilica/SimMath/releases/tag/sim-math-v1.6.0
* https://repo1.maven.org/maven2/org/jmonkeyengine/jme3-core/3.6.1-stable/
* https://repo1.maven.org/maven2/org/jmonkeyengine/jme3-terrain/3.6.1-stable/
* https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.32/

Vorrai sicuramente i file JAR delle classi e 
probabilmente anche i file JAR '-sources' e '-javadoc'.

Apri le proprietà del progetto nell'IDE (JME SDK o NetBeans):

. Fai clic con il tasto destro del mouse sul progetto (non sulla sua cartella "assets") nella finestra "Progetti".
. Seleziona il menu: Proprietà[] per aprire il dialogo delle "Proprietà del Progetto".
. Sotto 'Categorie:', clicca su btn:[Librerie].
. Clicca sulla scheda btn:[Compila].
. Aggiungi il file JAR delle classi di Heart:
.. Clicca sul pulsante btn:[Aggiungi JAR/Cartella].
.. Naviga nella cartella di download.
.. Seleziona il file "Minie-7.7.0.jar".
.. Clicca sul pulsante btn:[Apri].
. (opzionale) Aggiungi i file JAR per la documentazione Java (javadoc) e le sorgenti (sources):
.. Clicca sul pulsante btn:[Modifica].
.. Clicca sul pulsante btn:[Sfoglia...] a destra di "Javadoc:".
.. Seleziona il file "Minie-7.7.0-javadoc.jar".
.. Clicca sul pulsante btn:[Apri].
.. Clicca sul pulsante btn:[Sfoglia...] a destra di "Sorgenti:".
.. Seleziona il file "Minie-7.7.0-sources.jar".
.. Clicca nuovamente sul pulsante btn:[Apri].
.. Clicca sul pulsante btn:[OK] per chiudere il dialogo 'Modifica Riferimento JAR'.
. Aggiungi le altre librerie JVM nello stesso modo.
. Clicca sul pulsante btn:[OK] per uscire dal dialogo 'Proprietà del Progetto'.

== Carica la libreria nativa.

In un'applicazione convenzionale di JMonkeyEngine, le librerie native necessarie 
vengono caricate automaticamente tramite `Application.start()`.

Se la tua applicazione non richiama `Application.start()`, carica la
libreria nativa di Minie prima di istanziare qualsiasi oggetto fisico.

[source,java]
----
NativeLibraryLoader.loadNativeLibrary("bulletjme", true);
----

Per far funzionare Minie su piattaforme Android con Marshmallow (6.0) o versioni successive, 
assicurati che il flag `extractNativeLibs` sia impostato 
su `true` nell'elemento 'application' del file 'AndroidManifest.xml'.

== Collega un `BulletAppState`.

Riguardo a questo, Minie non richiede strettamente
un {url-api}/BulletAppState.html[`BulletAppState`]. 
Tuttavia, l'appstate fornisce un'interfaccia conveniente per configurare, 
accedere, aggiornare e debuggare uno {url-api}/PhysicsSpace.html[`PhysicsSpace`].

Se l'applicazione ha già un {url-api}/BulletAppState.html[`BulletAppState`], quel codice potrebbe funzionare con Minie. In caso contrario, ecco uno snippet per guidarti:

[source,java]
----
import com.jme3.bullet.BulletAppState;
import com.jme3.bullet.PhysicsSpace;

// ...

@Override
public void simpleInitApp() {
    BulletAppState bulletAppState = new BulletAppState();
    stateManager.attach(bulletAppState);
----

[CAUTION]
====
L''ordine di inizializzazione è importante. 
Un `BulletAppState` non può essere istanziato fino a quando la libreria nativa non è stata caricata, il che avviene durante Application.start() (per le app desktop). Ecco perché il seguente snippet fallisce:


[source,java]
----
static BulletAppState bulletAppState = new BulletAppState();
----
====

Per impostazione predefinita, la visualizzazione di debug è disabilitata. Per abilitarla, utilizza:

[source,java]
----
bulletAppState.setDebugEnabled(true); // default=false
----

Altri parametri di {url-api}/BulletAppState.html[`BulletAppState`] 
utilizzati per personalizzare la visualizzazione di debug 
sono descritti nella pagina di risoluzione dei problemi: xref:debug.adoc[pagina dei suggerimenti].

Le tecniche per simulare la fisica senza utilizzare {url-api}/BulletAppState.html[`BulletAppState`] sono descritte nella pagina della simulazione fisica senza appstate: xref:server.adoc[pagina della fisica senza appstate].

== Configura lo `PhysicsSpace`.

Collegando un {url-api}/BulletAppState.html[`BulletAppState`], si istanzia un {url-api}/PhysicsSpace.html[`PhysicsSpace`] a cui l''applicazione può accedere immediatamente:

[source,java]
----
PhysicsSpace space = bulletAppState.getPhysicsSpace();
----

La simulazione fisica può essere eseguita con un passo temporale fisso o variabile.
 La configurazione predefinita prevede un passo temporale fisso 
 di 1/60 di secondo con un massimo di 4 passi temporali per frame.

Per configurare un passo temporale variabile con un massimo di 0,25 secondi:

[source,java]
----
space.setMaxSubSteps(0);
space.setMaxTimeStep(0.25f);
----

Per configurare un passo temporale fisso di 0,01 secondi con un massimo di 6 passi temporali per frame:

[source,java]
----
space.setAccuracy(0.01f);
space.setMaxSubSteps(6);
----

NOTA: `setAccuracy()` non ha effetto quando `maxSubSteps`==0,
mentre `setMaxTimeStep()` non ha effetto quando `maxSubSteps`>0.

Ogni spazio fisico ha un vettore di gravità, 
che di solito viene applicato ai corpi quando vengono 
aggiunti allo spazio. Per simulare un ambiente a gravità zero, 
imposta la gravità dello spazio a zero:

[source,java]
----
space.setGravity(Vector3f.ZERO);
----

== Crea e aggiungi oggetti di collisione.

Gli oggetti di collisione possono essere di molti tipi diversi:

* corpi (`PhysicsBody`)
** corpi deformabili (`PhysicsSoftBody`)
** corpi rigidi (`PhysicsRigidBody`)
*** veicoli (`PhysicsVehicle`)
* oggetti ghost (`PhysicsGhostObject`)
* personaggi (`PhysicsCharacter`)
* collider (`MultiBodyCollider`)

Puoi crearli direttamente utilizzando i costruttori:

[source,java]
----
float radius = 2f;
CollisionShape sphere2 = new SphereCollisionShape(radius);
PhysicsGhostObject ghost1 = new PhysicsGhostObject(sphere2);
float mass = 1f;
PhysicsRigidBody body1 = new PhysicsRigidBody(sphere2, mass);
----

o indirettamente, aggiungendo controlli fisici agli spatial del grafo della scena:

[source,java]
----
float radius = 2f;
CollisionShape sphere2 = new SphereCollisionShape(radius);

Node ghostNode1 = new Node("ghostNode1");
GhostControl gc1 = new GhostControl(sphere2);
ghostNode1.addControl(gc1);

Node rigidNode1 = new Node("rigidNode1");
float mass = 1f;
RigidBodyControl rbc1 = new RigidBodyControl(sphere2, mass);
rigidNode1.addControl(rbc1);
----

In entrambi i casi, 
gli oggetti non vengono simulati a meno che non vengano aggiunti a uno spazio.

== Riassunto

* Prima di aggiungere Minie a un'applicazione, rimuovi tutte le altre librerie fisiche.
* {url-api}/BulletAppState.html[`BulletAppState`] fornisce un'interfaccia conveniente per configurare,
   accedere, aggiornare e debuggare uno spazio fisico.
* Gli oggetti di collisione possono essere creati in due modi:
** direttamente, utilizzando i costruttori
** indirettamente, aggiungendo controlli fisici al grafo della scena.
* Gli oggetti di collisione non vengono simulati a meno che non vengano aggiunti a uno spazio.
