= An introduction to character physics
:experimental:
:page-pagination:
:pi: &#960;
:url-api: https://stephengold.github.io/Minie/javadoc/master/com/jme3/bullet
:url-jme3test: https://github.com/stephengold/Minie/blob/master/Jme3Examples/src/main/java/jme3test
:url-tutorial: https://github.com/stephengold/Minie/blob/master/TutorialApps/src/main/java/jme3utilities/tutorial

Un _personaggio fisico_ è un oggetto di collisione 
utilizzato per simulare il movimento di personaggi di gioco (persone) mentre camminano, saltano e cadono.

Il personaggio fisico standard si basa su alcune semplificazioni concettuali:

* La forma del personaggio deve essere convessa.
* Il personaggio rimane in posizione eretta anche durante il salto o la caduta:
  nessuna seduta, accovacciamento, chinarsi o sdraiarsi.
* Vengono imposti dei limiti su:
** quanto ripido può essere una pendenza che il personaggio può scalare,
** quanto alta può essere uno scalino che il personaggio può superare, e
** quanto velocemente il personaggio può cadere.

Come un corpo rigido dinamico, 
un personaggio fisico ha una forma di collisione, una posizione e un vettore gravitazionale,
insieme a velocità e parametri di smorzamento. Dispone anche di un'opzione per la risposta ai contatti,
che è abilitata per impostazione predefinita.

Tuttavia, un personaggio fisico non ha un concetto di massa, e il suo movimento è controllato in modo molto diverso rispetto a un corpo dinamico. Invece di applicare forze o aggiornare direttamente le velocità del personaggio, l'applicazione dovrebbe specificare quando e come il personaggio dovrebbe camminare e saltare.

== Creazione diretta

Puoi creare un personaggio invocando direttamente il costruttore
{url-api}/objects/PhysicsCharacter.html[`PhysicsCharacter`].
Ciò ti consente di specificare la sua forma di collisione e l'altezza del gradino.

{url-tutorial}/HelloCharacter.java[HelloCharacter] È un'applicazione semplice che dimostra la creazione diretta di un personaggio, seguita da salti automatizzati.
Cose da notare riguardo all'applicazione:

. Il costruttore richiede una forma convessa. 
  In questa applicazione, viene utilizzata una capsula.
. Di per sé, il personaggio e il terreno sono entrambi invisibili, 
  quindi l'applicazione utilizza la visualizzazione di debug 
  per mostrare cosa sta accadendo nello spazio fisico.
. Il metodo `onGround()` verifica se il personaggio è supportato 
  da una superficie solida (contrariamente al salto o alla caduta).

Poiché i personaggi creati direttamente non hanno un aspetto molto dettagliato, nemmeno nella visualizzazione di debug, vengono principalmente utilizzati per rappresentare i giocatori nei giochi in single-player con una visuale in prima persona.

== CharacterControl

Per associare un personaggio a uno spatial, è disponibile la classe
{url-api}/control/CharacterControl.html[`CharacterControl`]
che implementa l'interfaccia {url-api}/control/PhysicsControl.html[`PhysicsControl`].

NOTA: Per il {url-api}/control/CharacterControl.html[`CharacterControl`],
Il controllo fisico e il suo oggetto di collisione *non* sono lo stesso oggetto! In realtà, nessun oggetto di collisione viene creato fino a quando il controllo viene aggiunto a uno spazio (spatial).

Per accedere all'oggetto di collisione associato a un controllo, utilizza `characterControl.getCharacter()`. Per accedere al controllo associato a un oggetto di collisione puoi utilizzare:

[source,java]
----
(CharacterControl) character.getUserObject();
----

{url-tutorial}/HelloCharacterControl.java[HelloCharacterControl]
È un'applicazione semplice che dimostra la creazione di un {url-api}/control/CharacterControl.html[`CharacterControl`].

Cose da notare riguardo all'applicazione:

. La forma di collisione del personaggio è una capsula.
. Il centro del modello Jaime è posizionato tra i suoi piedi.
  Se il controllo fosse attaccato direttamente al modello, 
  la sua forma di capsula sarebbe spostata rispetto al centro. 
  Per far corrispondere il modello alla fisica, il controllo viene invece collegato a un `centerNode` posizionato vicino al petto di Jaime.
. Poiché il controllo fornisce metodi di comodità come `onGround()` e `jump()`, l'applicazione non accede mai direttamente all'oggetto di collisione.

== Camminare

Il movimento a piedi di un personaggio è controllato dal suo vettore _walk direction_ vector.
Durante ciascun step di simulazione, la componente orizzontale della direzione di camminata viene aggiunta alla posizione del personaggio.
Per fermare il personaggio durante la camminata, invoca  `setWalkDirection(Vector3f.ZERO)`.

NOTA: Nonostante il nome, la direzione di camminata non deve necessariamente essere un vettore unitario.

{url-tutorial}/HelloWalk.java[HelloWalk] Dimostra il movimento
controllato dalla tastiera di un personaggio fisico.
Cose da notare durante l'esecuzione dell'app:

. Muovi il mouse per orientare la telecamera.
. Poiché l'app utilizza una visuale in prima persona, il personaggio è invisibile. 
  Tuttavia, *l'ombra* del personaggio può essere vista. Trovala!
. Premi kbd:[Space bar] per saltare.
. Premi kbd:[W] per camminare nella direzione della camera.
. Alcune delle montagne hanno pendenze troppo ripide per permettere al personaggio di scalarle.

Per un esempio che utilizza una visuale in terza persona,
consulta: {url-tutorial}/HelloWalkOtoCc.java[HelloWalkOtoCc].

. Premi kbd:[Space bar] per saltare.
. Premi kbd:[U] per camminare nella direzione della camera.
. Premi kbd:[H] per camminare verso la sinistra della camera.
. Premi kbd:[J] per camminare verso la direzione opposta della camera.
. Premi kbd:[K] per camminare verso la destra della camera.

== Configurazione

I parametri di configurazione descritti in questa sezione
si applicano sia a `PhysicsCharacter` che a `CharacterControl`. 
Il controllo fornisce metodi di comodità per ottenere/impostare alcuni di questi parametri. 
Gli altri possono essere accessi tramite `characterControl.getCharacter()`.

=== Gravitazione e direzione "su"

La _up direction_  di un personaggio fisico è un vettore unitario che punta
nella direzione opposta al suo vettore di gravità.
Per impostazione predefinita, la direzione su è (0, 1, 0) e
il vettore di gravità è (0, -29.4, 0).

NOTA: La gravità predefinita di un personaggio è 3 volte 
più forte rispetto alla gravità predefinita di un {url-api}/PhysicsSpace.html[`PhysicsSpace`].

NOTA: A differenza della gravità di un corpo rigido, 
la gravità di un personaggio non viene mai sovrascritta da alcuno spazio fisico.

Per modificare il vettore di gravità di un personaggio, 
utilizza `character.setGravity(Vector3f)`.

L'alterazione del vettore di gravità aggiorna automaticamente la direzione "su" del personaggio.

Per modificare la magnitudine della gravità di un personaggio (senza cambiare la sua direzione), 
utilizza: `character.setGravity(float)`.

Per modificare la direzione "su" di un personaggio, utilizza: `character.setUp(Vector3f)`.
L'alterazione della direzione "su" aggiorna automaticamente il vettore di gravità del personaggio.

=== Velocità di salto

Se un personaggio salta nella sua direzione "su", il tempo di salita previsto e l'altezza del salto sono determinati dalla sua gravità e dalla velocità di salto. In termini approssimativi:

[source,java]
----
float g = character.getGravity(null).length();
float v0 = character.getJumpSpeed();
float riseSeconds = v0 / g;
float jumpHeight = v0 * v0 / (2f * g);
----

La velocità di salto predefinita è di 10 psu.
Per modificare la velocità di salto di un personaggio, utilizza: `character.setJumpSpeed(float)`.

=== Velocità di caduta

_Fall speed_ limita la velocità di un personaggio in caduta.
Per essere realistico, la velocità di caduta dovrebbe essere maggiore della velocità di salto del personaggio.

La velocità di caduta predefinita è di 55 psu.
Per modificare la velocità di caduta di un personaggio, utilizza: `character.setFallSpeed(float)`.

=== Altezza del gradino

_Step height_ limita l'altezza massima di un gradino che il personaggio può superare.
Per essere realistico, dovrebbe essere inferiore all'altezza del personaggio.

L'altezza iniziale del gradino di un personaggio è impostata dal costruttore.
Per modificarla, utilizza: `character.setStepHeight(float)`.

=== Massima pendenza

_Maximum slope_ Limita quanto ripida può essere una pendenza che il personaggio può scalare.
Viene espressa come un angolo in radianti rispetto al piano orizzontale.

La pendenza massima predefinita è di {pi}/4, indicando un angolo di 45 gradi.
Per modificarla, usa: `character.setMaxSlope(float)`.

=== Risposta ai contatti

Come con un corpo rigido, è possibile disabilitare la risposta ai contatti di un personaggio utilizzando
`character.setContactResponse(false)`.

Disabilitando la risposta ai contatti di un personaggio, lo obbligherà a cadere, almeno fino a quando la risposta ai contatti non verrà nuovamente abilitata.

== BetterCharacterControl

Molte limitazioni dei
{url-api}/objects/PhysicsCharacter.html[`PhysicsCharacter`] e
{url-api}/control/CharacterControl.html[`CharacterControl`]
sono codificate direttamente in Bullet.
Per aggirare queste limitazioni, potresti desiderare di implementare i tuoi controlli fisici personalizzati per i personaggi.

{url-api}/control/BetterCharacterControl.html[`BetterCharacterControl`] (BCC)
Si tratta di un controllo fisico personalizzato che implementa l'azione di accovacciamento e la direzione dello sguardo. Puoi utilizzarlo come modello per implementare i tuoi controlli fisici personalizzati.

NOTA: BCC si basa
su {url-api}/objects/PhysicsRigidBody.html[`PhysicsRigidBody`],
e non su {url-api}/objects/PhysicsCharacter.html[`PhysicsCharacter`].

Ci sono molte differenze fra BCC e CharacterControl.
Per esempio:

. Gli oggetti di collisione sono posizionati in modo diverso.
  BCC posiziona l'oggetto di collisione vicino ai piedi del personaggio,
  mentre CharacterControl lo posiziona al centro, dove si troverebbero i fianchi di una persona.
. Le API per ricollocare istantaneamente il personaggio sono diverse.
  BCC fornisce un metodo `warp()`,
  mentre CharacterControl ti consente di invocare direttamente `setPhysicsLocation()`.
. I metodi `setWalkDirection()` hanno semantica diversa.
  In BCC, l'argomento è un vettore di velocità (unità per secondo),
  mentre in CharacterControl l'argomento è uno spostamento (unità per passo temporale).
. Le API per verificare se il personaggio ha supporto fisico sono diverse.
  BCC utilizza `isOnGround()`,
  mentre CharacterControl la chiama `onGround()`.
. Un CharacterControl attraverserà un altro CharacterControl senza collidere,
  mentre un BCC può rilevare collisioni con altri personaggi.
. Un BCC ha una massa e può essere configurato per il movimento cinematico,
  mentre un CharacterControl non ha massa e non può essere reso cinematico.
. Il BCC è più personalizzabile rispetto al CharacterControl.

{url-tutorial}/HelloWalkOtoBcc.java[HelloWalkOtoBcc] È un'applicazione semplice
che dimostra il camminare e saltare con BCC e una visuale in terza persona.
L'interfaccia utente è identica a HelloWalkOtoCc:

. Premi kbd:[Space bar] per saltare.
. Premi kbd:[U] Per camminare nella direzione in avanti della telecamera.
. Premi kbd:[H], kbd:[J], o kbd:[K] Per camminare in altre direzioni.

== Applicazioni demo correlate.

Il sottoprogetto Jme3Examples contiene diverse app demo
che presentano personaggi fisici.

* {url-jme3test}/bullet/TestQ3.java[The `TestQ3` demo app] Dimostra
  una passeggiata in prima persona all'interno di un tempio antico fittizio.
  Utilizza un `PhysicsCharacter` creato direttamente.
* Le {url-jme3test}/bullet/TestPhysicsCharacter.java[`TestPhysicsCharacter`]
  e {url-jme3test}/bullet/TestWalkingChar.java[`TestWalkingChar`]
  app demo utilizzano `CharacterControl` e una visuale in terza persona.
** TestWalkingCharacter dimostra il modello Oto che cammina e spara,
  con le relative animazioni del scheletro.
** TestPhysicsCharacter dimostra il modello Sinbad che cammina e salta,
  ma non utilizza animazioni del scheletro.
* {url-jme3test}/bullet/TestBetterCharacter.java[La `TestBetterCharacter` app demo]
  Dimostra il modello Jaime che cammina, salta e si accovaccia.
  Utilizza BCC e una visuale in terza persona.

== Sommario

* Un personaggio fisico simula un personaggio di gioco che cammina, salta e cade.
* Per associare un personaggio a uno spaziale, utilizza un `CharacterControl`.
* Per `CharacterControl`, il controllo fisico
  e il suo oggetto di collisione *non* sono lo stesso oggetto!
* Se i controlli di personaggio integrati non soddisfano le tue esigenze,
  puoi implementarne uno personalizzato.
